base: &base
  adapter: em_postgresql
  host: localhost
  username: mike
  password: password
  schema_search_path: public
  database: qanat_development
  statement_timeout: 60
  encoding: UTF8
  port: 5432

development:
  <<: *base

staging:
  <<: *base

test:
  <<: *base
  database: qanat_test
  
production: 
  <<: *base
  database: qanat_production
