base: &base
  adapter: em_postgresql
  host: dev-db-2.vpn.intspot.com
  username: bdu
  schema_search_path: bdu,public
  database: juneau
  statement_timeout: 60
  encoding: UTF8
  port: 5432

development:
  <<: *base

staging:
  <<: *base

test:
  <<: *base
  host: localhost
  username: mike
  password: password
  database: onespot_test
  
production: 
  <<: *base
  host: localhost
  database: prod_2
  port: 15432